Modules/Admin/Routes/web.php
<?php

Route::prefix('admin')->middleware('admin_auth')->group(function() {
//    После добавления маршрута необходимо создать разрешения для этого маршрута в
//    \App\Http\Middleware\CheckPermissions::class и в базе данных(или в сиде RolesAndPermissionsSeeder.php)

    Route::resource('/', 'DashboardController')
        ->only(['index'])->names('admin.dashboard');

    Route::resource('user', 'UserController')
        ->names('admin.user');

    Route::resource('permission', 'PermissionController')
        ->except(['create', 'store', 'destroy'])->names('admin.permission');

    Route::resource('role', 'RoleController')
        ->names('admin.role');

    Route::resource('user_role', 'UserRoleController')
        ->only(['index','show','edit','update'])->names('admin.user_role');
});

Modules/Admin/Models/Permissions.php
<?php

namespace Modules\Admin\Models;

use Illuminate\Database\Eloquent\Model;

class Permissions extends Model
{
    protected $fillable = [];
}

Modules/Admin/Http/Controllers/PermissionController.php
<?php

namespace Modules\Admin\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Modules\Admin\Models\Permissions;

class PermissionController extends Controller
{
    public $title = 'Разрешения';

    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        $permissions = Permissions::paginate();
        return view('admin::pages.permission.index', ['permissions' => $permissions, 'title' => $this->title, 'title_page' => 'Список разрешений']);
    }


    /**
     * Show the specified resource.
     * @param int $id
     * @return Response
     */
    public function show($id)
    {
        $permission = Permissions::where('id', $id)->first();
        return view('admin::pages.permission.show', ['permission' => $permission, 'title' => $this->title, 'title_page' => 'Просмотр разрешения']);
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Response
     */
    public function edit($id)
    {
        $permission = Permissions::where('id', $id)->first();
        return view('admin::pages.permission.edit', ['permission' => $permission, 'title' => $this->title, 'title_page' => 'Редактирование разрешения']);
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $desc = $request->input('description');
        Permissions::where('id', $id)->update(['description' => $desc]);
        return redirect()->back();
    }

}

Modules/Admin/Resources/views/pages/permission/edit.blade.php
@extends('admin::layouts.master')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <div class="card card-primary">
                    <div class="card-header card-primary">
                        <h6 class="card-title">Некоторые свойства можно редактировать только программно</h6>
                    </div>
                    <form role="form" action="{{ route('admin.permission.update', ['permission'=>$permission->id]) }}" method="post">
                        @csrf
                        @method('PATCH')
                        <div class="card-body">
                            <div class="form-group">
                                <label for="name">Ключ</label>
                                <input type="text" class="form-control" id="name" name="name"
                                       value="{{ $permission->name }}" disabled>
                            </div>
                            <div class="form-group">
                                <label for="description">Описание</label>
                                <input type="text" class="form-control" id="description" name="description"
                                       value="{{ $permission->description  }}" required>
                            </div>

                            <div class="form-group">
                                <label for="guard_name">Охранник</label>
                                <input type="text" class="form-control" id="guard_name" name="guard_name"
                                       value="{{ $permission->guard_name }}" disabled>
                            </div>

                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

Modules/Admin/Resources/views/pages/permission/index.blade.php
@extends('admin::layouts.master')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <!-- /.card-header -->
                    <div class="card-body table-responsive p-0">
                        <table class="table table-hover text-nowrap">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Description</th>
                                <th>Guard Name</th>
                                <th>Date</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($permissions as $permission)
                            <tr>
                                <td>{{ $permission->id }}</td>
                                <td>{{ $permission->name }}</td>
                                <td>{{ $permission->description }}</td>
                                <td>{{ $permission->guard_name }}</td>
                                <td>{{ $permission->created_at }}</td>
                                <td>
                                    <div class="btn-group btn-group-sm">
                                        <a href="{{ route('admin.permission.show', ['permission'=>$permission->id]) }}" class="btn btn-info" style="max-height: 30px"><i class="fas fa-eye"></i></a>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                    {{ $permissions->links() }}
                </div>
                <!-- /.card -->
            </div>
        </div>
    </div>
@endsection
@section('script')
{{--    <script src="{{asset('assets/admin/dist/js/demo.js')}}"></script>--}}
@endsection

Modules/Admin/Resources/views/pages/permission/show.blade.php
@extends('admin::layouts.master')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <div class="card card-primary">
                    <form role="form">
                        <div class="card-body">
                            <div class="form-group">
                                <label for="name">Ключ</label>
                                <input type="text" class="form-control" id="name" name="name"
                                       value="{{ $permission->name }}" disabled>
                            </div>
                            <div class="form-group">
                                <label for="birth_date">Описание</label>
                                <input type="text" class="form-control" id="birth_date" name="birth_date"
                                       value="{{ $permission->description }}" disabled>
                            </div>

                            <div class="form-group">
                                <label for="email">Охранник</label>
                                <input type="email" class="form-control" id="exampleInputEmail1" name="email"
                                       value="{{ $permission->guard_name }}" disabled>
                            </div>

                        </div>
                        <div class="card-footer">
                            <a href="{{ route('admin.permission.edit', ['permission' => $permission->id]) }}" class="btn btn-primary">Редактировать</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection